Repository arifiqra123/memorial, pull requests merged in 2024-10, with the labels that each got.

#1 change
  index.html
Labels: hecktoberfest2024

#2 first comm.....it
  index.html
Labels: hacktoberfest

#4 Zubair
  index.html
Labels: hacktoberfest

#5 ;;;
  index.html
Labels: hacktoberfest, hecktoberfest-accepted

#7 Zubair
  alerts.html
Labels: hecktoberfest-accepted

#9 Zubair
  alerts.html
Labels: hacktoberfest-accepted
